import mirrorCreator from 'mirror-creator';

export default mirrorCreator([
  'TOGGLE_MOBILE_FILTERS',

  'GET_FEATURED_COMPANIES_REQUEST',
  'GET_FEATURED_COMPANIES_SUCCESS',
  'GET_FEATURED_COMPANIES_FAILURE',

  'GET_SEARCH_PARAMS_REQUEST',
  'GET_SEARCH_PARAMS_SUCCESS',
  'GET_SEARCH_PARAMS_FAILURE',

  'GET_CURRENT_USER_REQUEST',
  'GET_CURRENT_USER_SUCCESS',
  'GET_CURRENT_USER_FAILURE',

  'SEARCH_JOBS_REQUEST',
  'SEARCH_JOBS_SUCCESS',
  'SEARCH_JOBS_FAULURE',

  'CHANGE_LOCALE',
]);
